"""
Prompts for the DBT Pipeline Generator Skill Pack.
"""

DBT_MODEL_PROMPT = """
You are an expert Analytics Engineer.
The user wants to save the current data insight into a dbt pipeline.

Convert the following SQL query into a robust dbt model.
Ensure you use `{{ ref('...') }}` or `{{ source('...', '...') }}` for table dependencies.

Original Query:
{sql_query}

Requirements:
1. Provide the dbt SQL model code.
2. Provide the accompanying dbt schema.yml for documentation and testing.

Format your response exactly as follows:

```sql
-- models/marts/{model_name}.sql
{{ config(materialized='table') }}

[YOUR DBT SQL HERE]
```

```yaml
# models/marts/schema.yml
version: 2

models:
  - name: {model_name}
    description: "Generated by Vanna based on user request."
    columns:
      # [ADD COLUMN DESCRIPTIONS HERE]
```
"""
